src/Entity/Project.php
<?php

namespace App\Entity;

use App\Repository\ProjectRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Validator\Validator\ValidatorInterface;

/**
 * @ORM\Entity(repositoryClass=ProjectRepository::class)
 */
class Project
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=100)
     */
    private $project_name;

    /**
     * @ORM\Column(type="text")
     */
    private $project_description;

    /**
     * @ORM\Column(type="date")
     */
    private $project_creation_date;

    /**
     * @ORM\Column(type="datetime")
     */
    private $project_deadline;

    /**
     * @ORM\Column(type="string", length=1)
     */
    private $project_status;

    /**
     * @ORM\ManyToOne(targetEntity=User::class, inversedBy="projects")
     * @ORM\JoinColumn(nullable=false)
     */
    private $user;

    /**
     * @ORM\OneToMany(targetEntity=Task::class, mappedBy="project", orphanRemoval=true)
     */
    private $tasks;

    public function __construct()
    {
        $this->tasks = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getProjectName(): ?string
    {
        return $this->project_name;
    }

    public function setProjectName(string $project_name): self
    {
        $this->project_name = $project_name;

        return $this;
    }

    public function getProjectDescription(): ?string
    {
        return $this->project_description;
    }

    public function setProjectDescription(string $project_description): self
    {
        $this->project_description = $project_description;

        return $this;
    }

    public function getProjectCreationDate(): ?\DateTimeInterface
    {
        return $this->project_creation_date;
    }

    public function setProjectCreationDate(\DateTimeInterface $project_creation_date): self
    {
        $this->project_creation_date = $project_creation_date;

        return $this;
    }

    public function getProjectDeadline(): ?\DateTimeInterface
    {
        return $this->project_deadline;
    }

    public function setProjectDeadline(\DateTimeInterface $project_deadline): self
    {
        $this->project_deadline = $project_deadline;

        return $this;
    }

    public function getProjectStatus(): ?string
    {
        return $this->project_status;
    }

    public function setProjectStatus(string $project_status): self
    {
        $this->project_status = $project_status;

        return $this;
    }

    public function getUser(): ?User
    {
        return $this->user;
    }

    public function setUser(?User $user): self
    {
        $this->user = $user;

        return $this;
    }

    /**
     * @return Collection|Task[]
     */
    public function getTasks(): Collection
    {
        return $this->tasks;
    }

    public function addTask(Task $task): self
    {
        if (!$this->tasks->contains($task)) {
            $this->tasks[] = $task;
            $task->setProject($this);
        }

        return $this;
    }

    public function removeTask(Task $task): self
    {
        if ($this->tasks->removeElement($task)) {
            // set the owning side to null (unless already changed)
            if ($task->getProject() === $this) {
                $task->setProject(null);
            }
        }

        return $this;
    }
}

src/Entity/Task.php
<?php

namespace App\Entity;

use App\Repository\TaskRepository;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Validator\Validator\ValidatorInterface;

/**
 * @ORM\Entity(repositoryClass=TaskRepository::class)
 */
class Task
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=100)
     */
    private $task_name;

    /**
     * @ORM\Column(type="text")
     */
    private $task_description;

    /**
     * @ORM\Column(type="date")
     */
    private $task_creation_date;

    /**
     * @ORM\Column(type="datetime")
     */
    private $task_deadline;

    /**
     * @ORM\Column(type="string", length=1)
     */
    private $task_status;

    /**
     * @ORM\ManyToOne(targetEntity=Project::class, inversedBy="tasks")
     * @ORM\JoinColumn(nullable=false)
     */
    private $project;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getTaskName(): ?string
    {
        return $this->task_name;
    }

    public function setTaskName(string $task_name): self
    {
        $this->task_name = $task_name;

        return $this;
    }

    public function getTaskDescription(): ?string
    {
        return $this->task_description;
    }

    public function setTaskDescription(string $task_description): self
    {
        $this->task_description = $task_description;

        return $this;
    }

    public function getTaskCreationDate(): ?\DateTimeInterface
    {
        return $this->task_creation_date;
    }

    public function setTaskCreationDate(\DateTimeInterface $task_creation_date): self
    {
        $this->task_creation_date = $task_creation_date;

        return $this;
    }

    public function getTaskDeadline(): ?\DateTimeInterface
    {
        return $this->task_deadline;
    }

    public function setTaskDeadline(\DateTimeInterface $task_deadline): self
    {
        $this->task_deadline = $task_deadline;

        return $this;
    }

    public function getTaskStatus(): ?string
    {
        return $this->task_status;
    }

    public function setTaskStatus(string $task_status): self
    {
        $this->task_status = $task_status;

        return $this;
    }

    public function getProject(): ?Project
    {
        return $this->project;
    }

    public function setProject(?Project $project): self
    {
        $this->project = $project;

        return $this;
    }
}

src/Entity/User.php
<?php

namespace App\Entity;

use App\Repository\UserRepository;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Security\Core\User\UserInterface;
use Symfony\Component\Validator\Validator\ValidatorInterface;

/**
 * @ORM\Entity(repositoryClass=UserRepository::class)
 */
class User implements UserInterface
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=180, unique=true)
     */
    private $email;

    /**
     * @ORM\Column(type="json")
     */
    private $roles = [];

    /**
     * @var string The hashed password
     * @ORM\Column(type="string")
     */
    private $password;

    /**
     * @ORM\Column(type="string", length=50)
     */
    private $firstname;

    /**
     * @ORM\Column(type="string", length=50)
     */
    private $lastname;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function setEmail(string $email): self
    {
        $this->email = $email;

        return $this;
    }

    /**
     * A visual identifier that represents this user.
     *
     * @see UserInterface
     */
    public function getUsername(): string
    {
        return (string) $this->email;
    }

    /**
     * @see UserInterface
     */
    public function getRoles(): array
    {
        $roles = $this->roles;
        // guarantee every user at least has ROLE_USER
        $roles[] = 'ROLE_USER';

        return array_unique($roles);
    }

    public function setRoles(array $roles): self
    {
        $this->roles = $roles;

        return $this;
    }

    /**
     * @see UserInterface
     */
    public function getPassword(): string
    {
        return (string) $this->password;
    }

    public function setPassword(string $password): self
    {
        $this->password = $password;

        return $this;
    }

    /**
     * @see UserInterface
     */
    public function getSalt()
    {
        // not needed when using the "bcrypt" algorithm in security.yaml
    }

    /**
     * @see UserInterface
     */
    public function eraseCredentials()
    {
        // If you store any temporary, sensitive data on the user, clear it here
        // $this->plainPassword = null;
    }

    public function getFirstname(): ?string
    {
        return $this->firstname;
    }

    public function setFirstname(string $firstname): self
    {
        $this->firstname = $firstname;

        return $this;
    }

    public function getLastname(): ?string
    {
        return $this->lastname;
    }

    public function setLastname(string $lastname): self
    {
        $this->lastname = $lastname;

        return $this;
    }
}

src/Form/ProjectType.php
<?php

namespace App\Form;

use App\Entity\Project;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\Extension\Core\Type\DateTimeType;
use Symfony\Component\Validator\Constraints\Length;

class ProjectType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('project_name', TextType::class, ['label' => 'Nom du projet'])
            ->add('project_description', TextType::class, [
                'required' => true,
                'constraints' => [new Length(['max' => 50])],
                'label' => 'Description du projet'
                ])
            // ->add('project_creation_date') Mettre (new \DateTime('now') dans le controller
            ->add('project_deadline', DateTimeType::class, [
                'required' => true,
                'label' => 'Deadline'
                ])
            ->add('project_status', TextType::class, [
                'required' => true,
                'constraints' => [new Length(['max' => 1])],
                'label' => 'Status (O : en cours, X : terminé)'
                ])
            // ->add('user') Récupérer ID de l'utilisateur connecté
        ;
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => Project::class,
        ]);
    }
}

src/Controller/ProjectController.php
<?php

namespace App\Controller;

use App\Entity\Project;
use\App\Entity\Task;
use\App\Entity\User;
use App\Form\ProjectType;
use App\Repository\ProjectRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\IsGranted;

/**
 * @Route("/project")
 */
class ProjectController extends AbstractController
{

    /**
     * Require ROLE_USER for only this controller method.
     * @IsGranted("ROLE_USER")
     * @Route("/", name="project_index", methods={"GET"})
     */
    public function projects(ProjectRepository $projectRepository): Response
    {
        return $this->render('project/index.html.twig', [
            'projects' => $projectRepository->findAll(),
        ]);
    }

    /**
     * @Route("/new", name="project_new", methods={"GET","POST"})
     */
    public function new(Request $request): Response
    {
        $project = new Project();
        $form = $this->createForm(ProjectType::class, $project);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $project->setUser($this->getUser());
            $project->setProjectCreationDate(new \DateTime('now'));
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->persist($project);
            $entityManager->flush();

            $this->addFlash('success','Votre projet à bien été créé.');
            return $this->redirectToRoute('project_index');
        }

        return $this->render('project/new.html.twig', [
            'project' => $project,
            'form' => $form->createView(),
        ]);
    }

    /**
     * Require ROLE_USER for only this controller method.
     * @IsGranted("ROLE_USER")
     * @Route("/{id}", name="project_show")
     */
    public function show(Project $project, int $id): Response
    {
        $projectRepository = $this->getDoctrine()->getRepository(Project::class);
        $project = $projectRepository->find($id);
        dump($project);
        $taskRepository = $this->getDoctrine()->getRepository(Task::class);
        $task = $taskRepository->findBy([
            'project'=>$project
        ]);
        dump($task);
        return $this->render('project/show.html.twig', [
            'project' => $project,
            'task' => $task
        ]);
    }

    /**
     * @Route("/{id}/edit", name="project_edit", methods={"GET","POST"})
     */
    public function edit(Request $request, Project $project): Response
    {
        $form = $this->createForm(ProjectType::class, $project);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $this->getDoctrine()->getManager()->flush();

            return $this->redirectToRoute('project_index');
        }

        return $this->render('project/edit.html.twig', [
            'project' => $project,
            'form' => $form->createView(),
        ]);
    }

    /**
     * Require ROLE_USER for only this controller method.
     * @IsGranted("ROLE_USER")
     * @Route("project/delete/{id}", name="project_delete", methods={"DELETE"})
     */
    public function delete(Request $request, Project $project): Response
    {
        if ($this->isCsrfTokenValid('delete'.$project->getId(), $request->request->get('_token'))) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->remove($project);
            $entityManager->flush();
            $this->addFlash(
                'success',
                'Votre projet a bien été supprimé'
            );
        }
        else {
            $this->addFlash(
                'danger',
                "Une erreur est survenue, nous n'avons pas pu supprimer votre projet"
              );
        }

        return $this->redirectToRoute('project_index');
    }
}

templates/project/_delete_form.html.twig
<form method="post" action="{{ path('project_delete', {'id': project.id}) }}" onsubmit="return confirm('Êtes-vous sûr de vouloir supprimer ce projet?');">
    <input type="hidden" name="_method" value="DELETE">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ project.id) }}">
    <button class="btn btn-danger mt-3">SUPPRIMER</button>
</form>

templates/project/_form.html.twig
{{ form_start(form) }}
    {{ form_widget(form) }}
    <button class="btn btn-danger btn-lg btn-block my-5">{{ button_label|default('Enregistrer le projet') }}</button>
{{ form_end(form) }}

templates/project/edit.html.twig
{% extends 'template.html.twig' %}

{% block title %}Modifier projet{% endblock %}

{% block main %}
    <h1 class="text-center mb-5">Modifier votre projet</h1>

    {{ include('project/_form.html.twig', {'button_label': 'Update'}) }}

    <div class="row justify-content-around mb-5">
        <button  class="btn btn-dark"><a href="{{ path('project_index') }}">Retourner à la liste des projets</a></button>
    </div>
{% endblock %}

templates/project/index.html.twig
{% extends 'template.html.twig' %}

{% block title %}Vos projets{% endblock %}

{% block main %}
    {% if app.user %}
        <div class="mb-5 text-center">
            Bonjour, vous êtes connécté sur le compte : {{ app.user.username }}, <a class="text-danger" href="{{ path('app_logout') }}">Déconnexion</a>
        </div>
    {% endif %}

    <h1 class="text-center">Voir vos projets</h1>
    <a href="{{ path('project_new') }}">Créer un nouveau projet</a>

    {% for project in projects %}
        <div class="my-5 text-center">
            <div class="card col-md-12 p-0 row">
                <div class="card-body p-0">
                    <div class="bg-dark text-white">
                        <h5 class="card-title p-3">{{ project.projectName }}</h5>
                    </div>
                    <div class="row d-flex justify-content-around pt-3">
                        <h6 class="card-subtitle mb-3 text-muted">Création : {{ project.projectCreationDate ? project.projectCreationDate|date('d-m-Y') : '' }}</h6>
                        <h6 class="card-subtitle mb-3 text-muted">Deadline : {{ project.projectDeadline ? project.projectDeadline|date('d-m-Y H:i:s') : '' }}</h6>
                    </div>    
                        <hr>
                        <p class="card-text">{{ project.projectDescription }}</p>
                        <hr>
                        <h6 class="card-subtitle mb-3 text-muted">Status : {{ project.projectStatus }}</h6>
                    <div class="bg-dark p-3 d-flex justify-content-around">
                        <a href="{{ path('project_show', {'id': project.id}) }}" class="card-link">Détails</a>
                        <a href="{{ path('project_edit', {'id': project.id}) }}" class="card-link">Modifier</a>
                        <a href="{{ path('archive') }}" class="card-link">Archiver</a>
                    </div>
                    <div class="bg-dark text-white pb-2">
                        {{ include('project/_delete_form.html.twig') }}
                    </div>
                </div>
            </div>
        </div>
    {% endfor %}

{% endblock %}

templates/project/new.html.twig
{% extends 'template.html.twig' %}

{% block title %}New Project{% endblock %}

{% block main %}
    <h1 class="mb-5 text-center">Créer un nouveau projet</h1>

    {{ include('project/_form.html.twig') }}

    <div class="mb-5 text-center">
        <a href="{{ path('project_index') }}">Retourner sur la page de vos projet</a>
    </div>
{% endblock %}

templates/project/show.html.twig
{% extends 'template.html.twig' %}

{% block title %}Consulter le projet{% endblock %}

{% block main %}
    {% if app.user %}
        <div class="mb-5 text-center">
            Bonjour, vous êtes connécté sur le compte : {{ app.user.username }}, <a class="text-danger" href="{{ path('app_logout') }}">Déconnexion</a>
        </div>
    {% endif %}

    <h1 class="text-center">Consulter le projet : </h1>

    <div class="row my-5 text-center">
        <div class="card col-md-12 p-0">
            <div class="card-body p-0">
                <div class="bg-dark text-white">
                    <h5 class="card-title p-3">{{ project.projectName }}</h5>
                </div>
                    <h6 class="card-subtitle mb-3 text-muted">Création : {{ project.projectCreationDate ? project.projectCreationDate|date('Y-m-d') : '' }}</h6>
                    <h6 class="card-subtitle mb-3 text-muted">Deadline : {{ project.projectDeadline ? project.projectDeadline|date('Y-m-d H:i:s') : '' }}</h6>
                    <hr>
                    <p class="card-text">{{ project.projectDescription }}</p>
                    <hr>
                    <h6 class="card-subtitle mb-3 text-muted">Status : {{ project.projectStatus }}</h6>
                <div class="bg-dark p-3 d-flex justify-content-around">
                    <a href="{{ path('project_index') }}" class="card-link">Projets</a>
                    <a href="{{ path('project_edit', {'id': project.id}) }}" class="card-link">Modifier</a>
                    <a href="#" class="card-link">Archiver</a>
                </div>
                <div class="bg-dark text-white pb-2 justify-content-around">
                    {{ include('project/_delete_form.html.twig') }}   
                </div>
            </div>
        </div>

        <div class="my-5 col-md-12">
        <a href="{{ path('task_new', {'id': project.id}) }}">Ajouter une nouvelle tâche.</a>

            <table class="table mt-5">
                <thead class="thead-dark">
                    <tr>
                        <th>Tâches</th>
                        <th>Description</th>
                        <th>Date de création</th>
                        <th>Deadline</th>
                        <th>Status (O:en cours, X:terminé)</th>
                        <th>Actions</th>
                    </tr>
                </thead>
                <tbody>
                {% for task in project.tasks %}
                    <tr>
                        <td>{{ task.taskName }}</td>
                        <td>{{ task.taskDescription }}</td>
                        <td>{{ task.taskCreationDate ? task.taskCreationDate|date('d-m-Y') : '' }}</td>
                        <td>{{ task.taskDeadline ? task.taskDeadline|date('d-m-Y H:i:s') : '' }}</td>
                        <td>{{ task.taskStatus }}</td>
                        <td>
                            <a href="{{ path('task_edit', {'id': task.id}) }}">Modifier</a>
                            {{ include('task/_delete_form.html.twig') }}
                        </td>
                    </tr>
                {% else %}
                    <tr>
                        <td colspan="7">no records found</td>
                    </tr>
                {% endfor %}
                </tbody>
            </table>
        </div>
    </div>

{% endblock %}